# ===================================
# Config file for github pages theme
# ===================================
# theme: jekyll-theme-minimal

# remote_theme: pages-themes/dinky@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# remote_theme: just-the-docs/just-the-docs
remote_theme: poole/lanyon
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
